servo_speed: 0.0095
angle_inc: 0.01745329251

min_ir_depth: 0.05
#min_pose_z is the minimum allowed height of Baxter's end effector. Figure this out by checking what the z position coordinate of /robot/limb/<side>/endpoint_state is when Baxter's gripper is close to its work surface
min_pose_z: -0.05

#desired_depth is the IR depth that will be commanded by reconstruct_3d to plan an initial trajectory before visual servoing beings.
desired_depth: 0.15

#the dimensions of Baxter's hand camera
camera_x: 640
camera_y: 400

goal_ratio_x: 0.5 
goal_ratio_y: 0.2 

object_height: 0.06

# UNUSED: these are the ratios where the edges of Baxter's grippers appear on its right camera, relative to the dimensions of the camera. So, if the width of the camera is 640, you can get the pixel value position of the innermost edge of the left gripper by gripper_min*640
gripper_min: 0.289
gripper_max: 0.75

rate: 500
button_rate: 0.5

threshold: 10
ir_thresh: 0.15
